name: Go CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21

    - name: Build the Application
      run: go build -o app

    - name: Build Docker Image
      run: docker build -t go-http-server .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to Google Cloud VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GCP_VM_IP }}
        username: ${{ secrets.GCP_VM_USER }}
        key: ${{ secrets.GCP_SSH_KEY }}
        script: |
          if [ ! -d "~/app" ]; then
            git clone https://github.com/Sathwikkd/Go-http-server.git ~/app
          else
            cd ~/app && git pull origin main
          fi
          docker stop go-http-server || true
          docker rm go-http-server || true
          docker rmi go-http-server || true
          docker build -t go-http-server ~/app
          docker run -d -p 8080:8080 --name go-http-server go-http-server

